/**
 * 国家名称映射表
 * 处理CSV数据中的国家名称和GeoJSON中的国家名称的差异
 */

// GDP CSV 国家名称映射
export const gdpCountryNameMapping = {
  'Andorra': 'Andorra',
  'Antigua and Barbuda': 'Antigua and Barbuda',
  'Bahamas, The': 'The Bahamas',
  'Bahrain': 'Bahrain',
  'Barbados': 'Barbados',
  'Brunei Darussalam': 'Brunei',
  'Cabo Verde': 'Cape Verde',
  'China, People\'s Republic of': 'China',
  'Comoros': 'Comoros',
  'Congo, Dem. Rep. of the': 'Democratic Republic of the Congo',
  'Congo, Republic of': 'Republic of the Congo',
  'Congo-Kinshasa': 'Democratic Republic of the Congo',
  'Congo-Brazzaville': 'Republic of the Congo',
  'Côte d\'Ivoire': 'Ivory Coast',
  'Czech Rep.': 'Czech Republic',
  'Dominica': 'Dominica',
  'Egypt, Arab Rep.': 'Egypt',
  'Eswatini': 'Swaziland',
  'Gambia, The': 'Gambia',
  'Grenada': 'Grenada',
  'Guinea-Bissau': 'Guinea Bissau',
  'Hong Kong SAR': 'Hong Kong',
  'Hong Kong SAR, China': 'Hong Kong',
  'Iran, Islamic Rep.': 'Iran',
  'Kiribati': 'Kiribati',
  'Korea, Dem. People\'s Rep.': 'North Korea',
  'Korea, Rep.': 'South Korea',
  'Korea, Republic of': 'South Korea',
  'Kyrgyz Rep.': 'Kyrgyzstan',
  'Kyrgyz Republic': 'Kyrgyzstan',
  'Lao PDR': 'Laos',
  'Lao P.D.R.': 'Laos',
  'Liechtenstein': 'Liechtenstein',
  'Macao SAR': 'Macao',
  'Macao SAR, China': 'Macao',
  'Macao SAR, PRC': 'Macao',
  'Maldives': 'Maldives',
  'Marshall Islands': 'Marshall Islands',
  'Mauritius': 'Mauritius',
  'Micronesia, Fed. States of': 'Micronesia',
  'Micronesia, Fed. Sts.': 'Micronesia',
  'Micronesia, Fed. Sts': 'Micronesia',
  'North Macedonia': 'Macedonia',
  'Czechia': 'Czech Republic',
  'Viet Nam': 'Vietnam',
  'Bahamas': 'The Bahamas',
  'The Bahamas': 'The Bahamas',
  'Palau': 'Palau',
  'Russian Federation': 'Russia',
  'Saint Kitts and Nevis': 'Saint Kitts and Nevis',
  'Saint Lucia': 'Saint Lucia',
  'Saint Vincent and the Grenadines': 'Saint Vincent and the Grenadines',
  'Samoa': 'Samoa',
  'San Marino': 'San Marino',
  'São Tomé and Príncipe': 'São Tomé and Príncipe',
  'Serbia': 'Republic of Serbia',
  'Seychelles': 'Seychelles',
  'Singapore': 'Singapore',
  'Slovak Rep.': 'Slovakia',
  'Slovak Republic': 'Slovakia',
  'South Sudan, Republic of': 'South Sudan',
  'St. Kitts and Nevis': 'Saint Kitts and Nevis',
  'St. Lucia': 'Saint Lucia',
  'St. Vincent and the Grenadines': 'Saint Vincent and the Grenadines',
  'Taiwan Province of China': 'Taiwan',
  'Tanzania': 'United Republic of Tanzania',
  'Timor-Leste': 'East Timor',
  'Tonga': 'Tonga',
  'Tuvalu': 'Tuvalu',
  'Turkey': 'Turkey',
  'Türkiye': 'Turkey',
  'Turkiye': 'Turkey',
  'Türkiye, Republic of': 'Turkey',
  'United Kingdom': 'United Kingdom',
  'United States': 'United States of America',
  'Venezuela, RB': 'Venezuela',
  'Virgin Islands (U.S.)': 'US Virgin Islands',
  'West Bank and Gaza': 'West Bank',
  'Yemen, Rep.': 'Yemen',
  'Zimbabwe': 'Zimbabwe'
};

// 人均GDP CSV 国家名称映射
export const perCapitaCountryNameMapping = {
  'Andorra': 'Andorra',
  'Antigua and Barbuda': 'Antigua and Barbuda',
  'Bahamas, The': 'The Bahamas',
  'Bahrain': 'Bahrain',
  'Barbados': 'Barbados',
  'Brunei Darussalam': 'Brunei',
  'Cabo Verde': 'Cape Verde',
  'China, People\'s Republic of': 'China',
  "China, People's Republic of": 'China',
  'China': 'China',
    'Micronesia, Fed. Sts.': 'Micronesia',
    'Micronesia, Fed. Sts': 'Micronesia',
  'Congo, Dem. Rep.': 'Democratic Republic of the Congo',
  'Congo, Rep.': 'Republic of the Congo',
  'Cote d\'Ivoire': 'Ivory Coast',
  'Czech Republic': 'Czech Republic',
    'Czechia': 'Czech Republic',
    'Macao SAR': 'Macao',
    'Macao SAR, PRC': 'Macao',
  'Dominica': 'Dominica',
  'Djibouti': 'Djibouti',
  'Egypt, Arab Rep.': 'Egypt',
  'Eswatini': 'Swaziland',
  'Gambia, The': 'Gambia',
  'Grenada': 'Grenada',
  'Guinea-Bissau': 'Guinea Bissau',
  'Hong Kong SAR, China': 'Hong Kong',
  'Iran, Islamic Rep.': 'Iran',
  'Kiribati': 'Kiribati',
  'Korea, Dem. People\'s Rep.': 'North Korea',
  'Korea, Rep.': 'South Korea',
  'Kyrgyz Republic': 'Kyrgyzstan',
  'Lao PDR': 'Laos',
  'Liechtenstein': 'Liechtenstein',
  'Macao SAR, China': 'Macao',
  'Maldives': 'Maldives',
  'Marshall Islands': 'Marshall Islands',
  'Mauritius': 'Mauritius',
  'Micronesia, Fed. States of': 'Micronesia',
  'North Macedonia': 'Macedonia',
  'Palau': 'Palau',
  'Russian Federation': 'Russia',
  'Saint Kitts and Nevis': 'Saint Kitts and Nevis',
  'Saint Lucia': 'Saint Lucia',
  'Saint Vincent and the Grenadines': 'Saint Vincent and the Grenadines',
  'Samoa': 'Samoa',
  'San Marino': 'San Marino',
  'Sao Tome and Principe': 'São Tomé and Príncipe',
  'Serbia': 'Republic of Serbia',
  'Seychelles': 'Seychelles',
  'Singapore': 'Singapore',
  'Slovak Republic': 'Slovakia',
  'South Sudan': 'South Sudan',
  'Taiwan': 'Taiwan',
  'Tanzania': 'United Republic of Tanzania',
  'Timor-Leste': 'East Timor',
  'Tonga': 'Tonga',
  'Tuvalu': 'Tuvalu',
  'Turkey': 'Turkey',
  'Turkiye': 'Turkey',
  'United Kingdom': 'United Kingdom',
  'United States': 'United States of America',
  'Venezuela, RB': 'Venezuela',
  'West Bank and Gaza': 'West Bank',
  'Yemen, Rep.': 'Yemen',
  'Zimbabwe': 'Zimbabwe'
};
